# Generated by Django 5.2.7 on 2025-10-20 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Febric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category_name', models.CharField(max_length=120)),
                ('category_id', models.BigIntegerField()),
                ('weight', models.BigIntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pattern', models.CharField(blank=True, max_length=120)),
                ('like', models.PositiveIntegerField(db_index=True, default=0)),
            ],
        ),
    ]
