# Generated by Django 5.2.7 on 2025-10-21 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabric', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Febric',
            new_name='Fabric',
        ),
    ]
