# Generated by Django 5.2.7 on 2026-04-20 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fabric", "0002_rename_febric_fabric"),
    ]

    operations = [
        migrations.AddField(
            model_name="fabric",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="fabric",
            name="is_recommended",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="fabric",
            name="is_visible",
            field=models.BooleanField(default=True),
        ),
    ]
